In [1]:
import os
try:
 os.remove('University.db')
except OSError:
 pass
import sqlite3
conn = sqlite3.connect('University.db')

In [10]:
! dir University.db

 Volume in drive C has no label.
 Volume Serial Number is 880F-5846

 Directory of c:\Users\HP\OneDrive\Documents\DSBACODINGTEST

21/10/2025  08:34 AM            16,384 University.db
               1 File(s)         16,384 bytes
               0 Dir(s)  52,974,522,368 bytes free

In [4]:
import pandas as pd
student = pd.read_csv("datasets/student.csv")
course = pd.read_csv("datasets/course.csv")
grade = pd.read_csv("datasets/grade.csv")

In [5]:
student.to_sql('Student', con = conn, index = False)
course.to_sql('Course', con = conn, index = False)
grade.to_sql('Grade', con = conn, index = False)

8

In [6]:
c = conn.cursor()

In [7]:
c.execute('''
SELECT name
FROM sqlite_master
WHERE type='table'
''')

In [8]:
c.fetchall()

[('Student',), ('Course',), ('Grade',)]

In [9]:
import pandas as pd
q = c.execute("SELECT * FROM Student").fetchall()
pd.DataFrame(q)

           0               1  2
0  201921323       Ava Smith  2
1  201832220     Ben Johnson  3
2  202003219   Charlie Jones  1
3  202045234      Dan Norris  1
4  201985603      Emily Wood  1
5  201933222  Freddie Harris  2
6  201875940    Grace Clarke  2

In [11]:
c.execute('''
CREATE TABLE Teacher (staff_id TEXT PRIMARY KEY,
name TEXT)
''')

In [12]:
c.execute('''
SELECT name
FROM sqlite_master
WHERE type='table'
''').fetchall()

[('Student',), ('Course',), ('Grade',), ('Teacher',)]

Delete a Table
We can delete a table by running the SQL command through execute():

In [13]:
c.execute("DROP TABLE Teacher")

In [21]:
conn.commit()

In [15]:
c.execute('''
SELECT name
FROM sqlite_master
WHERE type='table'
''').fetchall()

[('Student',), ('Course',), ('Grade',)]

In [16]:
c.execute("INSERT INTO Student VALUES(202029744, 'Harper Taylor', 1)")

In [18]:
q = c.execute("SELECT * FROM Student").fetchall()
pd.DataFrame(q)

           0               1  2
0  201921323       Ava Smith  2
1  201832220     Ben Johnson  3
2  202003219   Charlie Jones  1
3  202045234      Dan Norris  1
4  201985603      Emily Wood  1
5  201933222  Freddie Harris  2
6  201875940    Grace Clarke  2
7  202029744   Harper Taylor  1

In [19]:
student

   student_id            name  year
0   201921323       Ava Smith     2
1   201832220     Ben Johnson     3
2   202003219   Charlie Jones     1
3   202045234      Dan Norris     1
4   201985603      Emily Wood     1
5   201933222  Freddie Harris     2
6   201875940    Grace Clarke     2

In [20]:
c.execute('''
UPDATE Student
SET student_id = "201929744"
WHERE name = "Harper Taylor"
''')

In [22]:
q = c.execute("SELECT * FROM Student").fetchall()
pd.DataFrame(q)

           0               1  2
0  201921323       Ava Smith  2
1  201832220     Ben Johnson  3
2  202003219   Charlie Jones  1
3  202045234      Dan Norris  1
4  201985603      Emily Wood  1
5  201933222  Freddie Harris  2
6  201875940    Grace Clarke  2
7  201929744   Harper Taylor  1

In [ ]:
c.execute('''
DELETE FROM Student
where name = "Harper Taylor"
''')

In [24]:
conn.commit()

In [25]:
import sqlite3
conn = sqlite3.connect('University.db')
c = conn.cursor()
c.execute("SELECT name FROM sqlite_master WHERE type='table'").fetchall()

[('Student',), ('Course',), ('Grade',)]

In [26]:
q1 = c.execute('''
SELECT final_mark
FROM Grade
WHERE course_id = 'ST101'
''').fetchall()
import pandas as pd
pd.DataFrame(q1)

    0
0  78
1  60
2  47

In [27]:
q2 = c.execute('''
SELECT Student.name
FROM Grade, Student
WHERE Grade.course_id = 'ST101' AND Student.student_id = Grade.student_id
ORDER BY Student.name
''').fetchall()
pd.DataFrame(q2)

               0
0      Ava Smith
1  Charlie Jones
2     Emily Wood

In [28]:
q3 = c.execute('''
SELECT DISTINCT Course.name
FROM Student, Grade, Course
WHERE (Student.name ='Ava Smith' OR Student.name = 'Freddie Harris') AND
Student.student_id = Grade.student_id AND Course.course_id = Grade.course_id
''').fetchall()
pd.DataFrame(q3)

                               0
0   programming for data science
1  Managing and Visualising Data
2                      Databases

In [29]:
q4 = c.execute('''
SELECT course_id, AVG(final_mark) as avg_mark
FROM Grade
GROUP BY course_id
''').fetchall()
pd.DataFrame(q4)

       0          1
0  ST101  61.666667
1  ST115  82.333333
2  ST207  66.500000

In [30]:
conn.close()