In [3]:
import pandas as pd
import numpy as np  
import matplotlib.pyplot as plt

In [5]:
df = pd.read_csv('C:\\Users\\HP\\OneDrive\\Documents\\DSBACODINGTEST\\titanic_799cd475e5a09b32d47aeb2d232ce93d.csv')
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,Unnamed: 15
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,NaN
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,NaN
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,NaN
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,NaN
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,NaN

In [7]:
df.describe()

,survived,pclass,age,sibsp,parch,fare,Unnamed: 15
count,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000,0.0
mean,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208,NaN
std,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429,NaN
min,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000,NaN
25%,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400,NaN
50%,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200,NaN
75%,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000,NaN
max,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200,NaN

In [17]:

n=0
for i in df["sex"]:
    if i == "male":
        n=n+1
    
print(n)

577

In [18]:
df[df.sex == "male"].count()

survived       577
pclass         577
sex            577
age            453
sibsp          577
parch          577
fare           577
embarked       577
class          577
who            577
adult_male     577
deck           106
embark_town    577
alive          577
alone          577
Unnamed: 15      0
dtype: int64